/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.mmaroti.ua.cspgen;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int VARIABLE = 5;
  /** RegularExpression Id. */
  int OPERATION = 6;
  /** RegularExpression Id. */
  int SIZE = 7;
  /** RegularExpression Id. */
  int ARITY = 8;
  /** RegularExpression Id. */
  int CONSTANT = 9;
  /** RegularExpression Id. */
  int VALUE = 10;
  /** RegularExpression Id. */
  int RELATION = 11;
  /** RegularExpression Id. */
  int CONSTRAINT = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int IMPLIES = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int NOTEQUALS = 18;
  /** RegularExpression Id. */
  int LESSTHAN = 19;
  /** RegularExpression Id. */
  int LESSTHANEQUALS = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int NAME = 24;
  /** RegularExpression Id. */
  int LPAR = 25;
  /** RegularExpression Id. */
  int RPAR = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"variable\"",
    "\"operation\"",
    "\"size\"",
    "\"arity\"",
    "\"constant\"",
    "\"value\"",
    "\"relation\"",
    "\"constraint\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"->\"",
    "\"=\"",
    "<NOTEQUALS>",
    "\"<\"",
    "\"<=\"",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<NAME>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
